param(
    [string]$Python = "python",
    [string]$EvidencePath = "evidence/EVID-PY-PONG-WINDOWS.json"
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
Push-Location $ProjectRoot

try {
    & $Python -m unittest discover -s tests -q
    if ($LASTEXITCODE -ne 0) { throw "Core tests failed." }

    $process = Start-Process -FilePath $Python -ArgumentList "-m", "pong.app" -PassThru
    Start-Sleep -Seconds 2
    if ($process.HasExited) { throw "Pong window exited before manual smoke checks." }

    Write-Host "Check the real Pong window. Do not mark PASS without performing every action."
    $checks = [ordered]@{
        window_visible = (Read-Host "Window and score are visible? [y/N]") -eq "y"
        left_controls = (Read-Host "W/S move the left paddle? [y/N]") -eq "y"
        right_controls = (Read-Host "Arrow keys move the right paddle? [y/N]") -eq "y"
        pause_resume = (Read-Host "Space pauses and resumes the ball? [y/N]") -eq "y"
        restart = (Read-Host "R resets score and match state? [y/N]") -eq "y"
        stable_60_seconds = (Read-Host "Window remained responsive for at least 60 seconds? [y/N]") -eq "y"
    }

    if (-not $process.HasExited) { Stop-Process -Id $process.Id }
    $passed = -not ($checks.Values -contains $false)
    $record = [ordered]@{
        schema_version = "0.1.0"
        evidence_id = "EVID-GUI-WIN-0001"
        project_id = "GAME-PY-L1-PONG-0001"
        recorded_at = (Get-Date).ToString("o")
        platform = [System.Environment]::OSVersion.VersionString
        python = (& $Python --version 2>&1).ToString()
        operator = $env:USERNAME
        automated_core_tests = "passed"
        manual_checks = $checks
        decision = $(if ($passed) { "pass" } else { "fail" })
        note = "Operator-attested manual GUI smoke; not generated by CI."
    }
    $record | ConvertTo-Json -Depth 5 | Set-Content -Encoding utf8 $EvidencePath
    Write-Host "Evidence written to $EvidencePath. Review it before committing."
    if (-not $passed) { exit 1 }
}
finally {
    if ($process -and -not $process.HasExited) { Stop-Process -Id $process.Id }
    Pop-Location
}

